[project]
name = "daily-news-dashboard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas-stubs~=2.3.3",
    "pydantic-settings>=2.12.0",
    "pyyaml>=6.0.3",
    "streamlit>=1.52.2",
]
